name: Update exchange rates
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Run app.js
        run: npm start
      - run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add exchange-rates.json
          git commit -m "Update exchange rates"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}