name: Manual Workflow on PR
on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
        
      - name: Run app.js
        run: npm start
      
      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add exchange-rates.json
          git commit -m "Update exchange rates"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}